INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-1-DAY-FILING-PRIOR','Required days before filing 1 day or less Force Leave \r\n','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-APPROVAL-CUTOFF','Force Leave advance approval allowable cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-APPROVAL-DAYS','Force Leave advance approval allowable days','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-APPROVAL-NOT-ALLOWED','Force Leave advance approval not allowed','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-APPROVAL-WITHIN-CUTOF','Force Leave advance approval allowed within cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-CANCELLATION-CUTOFF','Force Leave advance cancellation allowable cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-CANCELLATION-DAYS','Force Leave advance cancellation allowable days','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-CANCELLATION-NOT-ALLOWED','Force Leave advance cancellation not allowed','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-CANCELLATION-WITHIN-CUTOFF','Force Leave advance cancellation allowed within cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-FILING-CUTOFF','Force Leave advance filing allowable cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-FILING-DAYS','Force Leave advance filing allowable days','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-FILING-NOT-ALLOWED','Force Leave advance filing not allowed','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ADVANCE-FILING-WITHIN-CUTOFF','Force Leave advance filing allowed within cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-ALLOW-FILING-NO-CREDIT','Allow filing of Force Leave with zero credit','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-FILING-MAXIMUM-DAYS','Force Leave maximum allowable days','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-FILING-TENURE','Tenure to allow Force Leave filing','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-GRANT','Force Leave grant','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-HR-VALIDATION-DAYS','No. of days to undergo HR validation','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-APPROVAL-CUTOFF','Force Leave late approval allowable cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-APPROVAL-DAYS','Force Leave late approval allowable days','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-APPROVAL-NOT-ALLOWED','Force Leave late approval not allowed','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-APPROVAL-WITHIN-CUTOFF','Force Leave late approval allowed within cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-CANCELLATION-CUTOFF','Force Leave late cancellation allowable cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-CANCELLATION-DAYS','Force Leave late cancellation allowable days','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-CANCELLATION-NOT-ALLOWED','Force Leave late cancellation not allowed','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-CANCELLATION-WITHIN-CUTOFF','Force Leave late cancellation allowed within cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-FILING-CUTOFF','Force Leave late filing allowable cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-FILING-DAYS','Force Leave late filing allowable days','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-FILING-NOT-ALLOWED','Force Leave late filing not allowed','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-LATE-FILING-WITHIN-CUTOFF','Force Leave late filing allowed within cut-off ','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-MORE-THAN-A-DAY-FILING-PRIOR','Required days before filing more than 1 day Force Leave','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-REQUIRE-ATTACHMENT-DAYS','No. of days to require attachment','0');
INSERT INTO `ww_time_form_class` (`form_id`, `form_code`, `class_code`, `class`, `deleted`) VALUES('23','FLV','FLV-UNSCHEDULED-LATE-FILING-HOURS','Required hours to file late/unscheduled Force Leave','0');