<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['training_course.position_id'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Position',
	'description' => '',
	'table' => 'training_course',
	'column' => 'position_id',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_position',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'position',
		'value' => 'position_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['training_course.remarks'] = array(
	'f_id' => 11,
	'fg_id' => 2,
	'label' => 'Remarks',
	'description' => '',
	'table' => 'training_course',
	'column' => 'remarks',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['training_course.length_of_service'] = array(
	'f_id' => 10,
	'fg_id' => 2,
	'label' => 'Length of Service',
	'description' => '',
	'table' => 'training_course',
	'column' => 'length_of_service',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['training_course.cost'] = array(
	'f_id' => 9,
	'fg_id' => 2,
	'label' => 'Cost',
	'description' => '',
	'table' => 'training_course',
	'column' => 'cost',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['training_course.with_bond'] = array(
	'f_id' => 8,
	'fg_id' => 2,
	'label' => 'With Bond',
	'description' => '',
	'table' => 'training_course',
	'column' => 'with_bond',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_course.planned'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Is Planned?',
	'description' => '',
	'table' => 'training_course',
	'column' => 'planned',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_course.facilitator'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Facilitator',
	'description' => '',
	'table' => 'training_course',
	'column' => 'facilitator',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_course.provider_id'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Provider',
	'description' => '',
	'table' => 'training_course',
	'column' => 'provider_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_provider',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'provider',
		'value' => 'provider_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['training_course.type_id'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Type',
	'description' => '',
	'table' => 'training_course',
	'column' => 'type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'type',
		'value' => 'type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['training_course.category_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Category',
	'description' => '',
	'table' => 'training_course',
	'column' => 'category_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_category',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'category',
		'value' => 'category_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['training_course.course'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Course',
	'description' => '',
	'table' => 'training_course',
	'column' => 'course',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
