<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
$config["detail_cached_query"] = 'SELECT 
	`ww_payroll_partners`.`user_id` as record_id, 
	`ww_payroll_partners`.`created_on` as "payroll_partners.created_on", 
	`ww_payroll_partners`.`created_by` as "payroll_partners.created_by", 
	`ww_payroll_partners`.`modified_on` as "payroll_partners.modified_on", 
	`ww_payroll_partners`.`modified_by` as "payroll_partners.modified_by", 
	`ww_payroll_partners`.`user_id` as "payroll_partners.user_id", 
	`ww_payroll_partners`.`company_id` as "payroll_partners.company_id", 
	`ww_payroll_partners`.`total_year_days` as "payroll_partners.total_year_days", 
	`ww_payroll_partners`.`payroll_rate_type_id` as "payroll_partners.payroll_rate_type_id", 
	`ww_payroll_partners`.`payroll_schedule_id` as "payroll_partners.payroll_schedule_id", 
	CAST( AES_DECRYPT( `ww_payroll_partners`.`salary`, encryption_key()) AS CHAR) as "payroll_partners.salary", 
	`ww_payroll_partners`.`payroll_schedule_id` as "payroll_partners.payroll_schedule_id", 
	`ww_payroll_partners`.`taxcode_id` as "payroll_partners.taxcode_id", 
	CAST( AES_DECRYPT( `ww_payroll_partners`.`minimum_takehome`, encryption_key()) AS CHAR) as "payroll_partners.minimum_takehome", 
	`ww_payroll_partners`.`account_type_id` as "payroll_partners.account_type_id",
	`ww_payroll_partners`.`bank_id` as "payroll_partners.bank_id", 
	`ww_payroll_partners`.`bank_account` as "payroll_partners.bank_account", 
	`ww_payroll_partners`.`payment_type_id` as "payroll_partners.payment_type_id", 
	`ww_payroll_partners`.`fixed_rate` as "payroll_partners.fixed_rate", 
	`ww_payroll_partners`.`sensitivity` as "payroll_partners.sensitivity", 
	`ww_payroll_partners`.`sss_no` as "payroll_partners.sss_no", 
	`ww_payroll_partners`.`sss_mode` as "payroll_partners.sss_mode", 
	CAST( AES_DECRYPT( `ww_payroll_partners`.`sss_amount`, encryption_key()) AS CHAR) as "payroll_partners.sss_amount", 
	`ww_payroll_partners`.`sss_week` as "payroll_partners.sss_week", 
	`ww_payroll_partners`.`hdmf_no` as "payroll_partners.hdmf_no", 
	`ww_payroll_partners`.`hdmf_mode` as "payroll_partners.hdmf_mode", 
	CAST( AES_DECRYPT( `ww_payroll_partners`.`hdmf_amount`, encryption_key()) AS CHAR) as "payroll_partners.hdmf_amount", 
	`ww_payroll_partners`.`hdmf_week` as "payroll_partners.hdmf_week", 
	`ww_payroll_partners`.`phic_no` as "payroll_partners.phic_no",
	`ww_payroll_partners`.`phic_mode` as "payroll_partners.phic_mode", 
	CAST( AES_DECRYPT( `ww_payroll_partners`.`phic_amount`, encryption_key()) AS CHAR) as "payroll_partners.phic_amount", 
	`ww_payroll_partners`.`phic_week` as "payroll_partners.phic_week", 
	`ww_payroll_partners`.`tin` as "payroll_partners.tin", 
	`ww_payroll_partners`.`tax_mode` as "payroll_partners.tax_mode", 
	CAST( AES_DECRYPT( `ww_payroll_partners`.`tax_amount`, encryption_key()) AS CHAR) as "payroll_partners.tax_amount", 
	`ww_payroll_partners`.`tax_week` as "payroll_partners.tax_week", 
	`ww_payroll_partners`.`ecola_week` as "payroll_partners.ecola_week",
	DATE_FORMAT(`ww_partners`.`resigned_date`, \'%M %d, %Y\') as "partners.resigned_date",
	`ww_payroll_partners`.`attendance_base` as "payroll_partners.attendance_base", 
	`ww_payroll_partners`.`whole_half` as "payroll_partners.whole_half",
	`ww_payroll_partners`.`payout_schedule` as "payroll_partners.payout_schedule",
	`ww_payroll_partners`.`on_hold` as "payroll_partners.on_hold", 
	`ww_payroll_partners`.`location_id` as "payroll_partners.location_id",
	`ww_payroll_partners`.`non_swipe` as "payroll_partners.non_swipe"
FROM (`ww_payroll_partners`), (`ww_partners`)
WHERE `ww_payroll_partners`.`user_id` = `ww_partners`.`user_id`
	AND`ww_payroll_partners`.`user_id` = "{$record_id}"';