<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['payroll_partners.user_id'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Employee',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'user_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'full_name',
		'value' => 'user_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners.company_id'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Company',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'company_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_company',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'company',
		'value' => 'company_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners.total_year_days'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Total year days',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'total_year_days',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners.payroll_rate_type_id'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Rate Type',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'payroll_rate_type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_rate_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'payroll_rate_type',
		'value' => 'payroll_rate_type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners.payroll_schedule_id'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Payroll Schedule',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'payroll_schedule_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_schedule',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'payroll_schedule',
		'value' => 'payroll_schedule_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners.salary'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Rate',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'salary',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required|numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][1]['payroll_partners.taxcode_id'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Tax Code',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'taxcode_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'taxcode',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'taxcode',
		'value' => 'taxcode_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners.minimum_takehome'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Minimum Takehome',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'minimum_takehome',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][1]['payroll_partners.bank_id'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Bank Name',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'bank_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_bank',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'bank',
		'value' => 'bank_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners.bank_account'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Bank Account',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'bank_account',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners.account_type_id'] = array(
	'f_id' => 27,
	'fg_id' => 1,
	'label' => 'Account Type',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'account_type_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners.payment_type_id'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Payment Type',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'payment_type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_payment_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'payment_type',
		'value' => 'payment_type_id',
		'textual_value_column' => ''
	)
);

$config['fields'][1]['payroll_partners.location_id'] = array(
	'f_id' => 10,
	'fg_id' => 1,
	'label' => 'Payroll Location',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'location_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_location',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'location',
		'value' => 'location_id',
		'textual_value_column' => ''
	)
);

$config['fields'][1]['payroll_partners.fixed_rate'] = array(
	'f_id' => 11,
	'fg_id' => 1,
	'label' => 'Fixed Rate',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'fixed_rate',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners.sensitivity'] = array(
	'f_id' => 12,
	'fg_id' => 1,
	'label' => 'Sensitivity',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'sensitivity',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 12,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'sensitivity',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'sensitivity',
		'value' => 'sensitivity_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['payroll_partners.resigned_date'] = array(
	'f_id' => 13,
	'fg_id' => 2,
	'label' => 'Resigned Date',
	'description' => '',
	'table' => 'partners',
	'column' => 'resigned_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 13,
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners.attendance_base'] = array(
	'f_id' => 14,
	'fg_id' => 1,
	'label' => 'Attendance Base',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'attendance_base',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 14,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners.whole_half'] = array(
	'f_id' => 14,
	'fg_id' => 1,
	'label' => 'Whole Salary',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'whole_half',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 14,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners.payout_schedule'] = array(
	'f_id' => 14,
	'fg_id' => 1,
	'label' => 'Whole Salary',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'payout_schedule',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 14,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners.on_hold'] = array(
	'f_id' => 15,
	'fg_id' => 1,
	'label' => 'On Hold',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'on_hold',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 15,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['payroll_partners.sss_no'] = array(
	'f_id' => 11,
	'fg_id' => 2,
	'label' => 'SSS No.',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'sss_no',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['payroll_partners.sss_mode'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'SSS Transaction Mode',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'sss_mode',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_transaction_mode',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'payroll_transaction_mode',
		'value' => 'payroll_transaction_mode_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['payroll_partners.sss_amount'] = array(
	'f_id' => 13,
	'fg_id' => 2,
	'label' => 'Amount',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'sss_amount',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][2]['payroll_partners.sss_week'] = array(
	'f_id' => 14,
	'fg_id' => 2,
	'label' => 'Week',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'sss_week',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_week',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'week',
		'value' => 'week_id',
		'textual_value_column' => ''
	)
);
$config['fields'][3]['payroll_partners.hdmf_no'] = array(
	'f_id' => 15,
	'fg_id' => 3,
	'label' => 'PagIbig No.',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'hdmf_no',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['payroll_partners.hdmf_mode'] = array(
	'f_id' => 16,
	'fg_id' => 3,
	'label' => 'HDMF Transaction Mode',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'hdmf_mode',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_transaction_mode',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'payroll_transaction_mode',
		'value' => 'payroll_transaction_mode_id',
		'textual_value_column' => ''
	)
);
$config['fields'][3]['payroll_partners.hdmf_amount'] = array(
	'f_id' => 17,
	'fg_id' => 3,
	'label' => 'Amount',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'hdmf_amount',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][3]['payroll_partners.hdmf_week'] = array(
	'f_id' => 18,
	'fg_id' => 3,
	'label' => 'Week',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'hdmf_week',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_week',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'week',
		'value' => 'week_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['payroll_partners.phic_no'] = array(
	'f_id' => 19,
	'fg_id' => 4,
	'label' => 'PhilHealth No.',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'phic_no',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['payroll_partners.phic_mode'] = array(
	'f_id' => 20,
	'fg_id' => 4,
	'label' => 'PHIC Transaction Mode',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'phic_mode',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_transaction_mode',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'payroll_transaction_mode',
		'value' => 'payroll_transaction_mode_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['payroll_partners.phic_amount'] = array(
	'f_id' => 21,
	'fg_id' => 4,
	'label' => 'Amount',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'phic_amount',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][4]['payroll_partners.phic_week'] = array(
	'f_id' => 22,
	'fg_id' => 4,
	'label' => 'Week',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'phic_week',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_week',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'week',
		'value' => 'week_id',
		'textual_value_column' => ''
	)
);
$config['fields'][5]['payroll_partners.tin'] = array(
	'f_id' => 23,
	'fg_id' => 5,
	'label' => 'TIN',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'tin',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['payroll_partners.tax_mode'] = array(
	'f_id' => 24,
	'fg_id' => 5,
	'label' => 'WHTAX Transaction Mode',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'tax_mode',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_transaction_mode_tax',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'payroll_transaction_mode',
		'value' => 'payroll_transaction_mode_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['payroll_partners.tax_amount'] = array(
	'f_id' => 27,
	'fg_id' => 5,
	'label' => 'Amount',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'tax_amount',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][5]['payroll_partners.tax_week'] = array(
	'f_id' => 25,
	'fg_id' => 5,
	'label' => 'Week',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'tax_week',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_week',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'week',
		'value' => 'week_id',
		'textual_value_column' => ''
	)
);
$config['fields'][6]['payroll_partners.ecola_week'] = array(
	'f_id' => 26,
	'fg_id' => 6,
	'label' => 'Week',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'ecola_week',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_week',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'week',
		'value' => 'week_id',
		'textual_value_column' => ''
	)
);

$config['fields'][1]['payroll_partners.non_swipe'] = array(
	'f_id' => 10,
	'fg_id' => 1,
	'label' => 'Non Swipe',
	'description' => '',
	'table' => 'payroll_partners',
	'column' => 'non_swipe',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
