<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][7]['users_position.position'] = array(
	'f_id' => 1,
	'fg_id' => 7,
	'label' => 'Position',
	'description' => '',
	'table' => 'users_position',
	'column' => 'position',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['users_position.position_code'] = array(
	'f_id' => 2,
	'fg_id' => 7,
	'label' => 'Position Code',
	'description' => '',
	'table' => 'users_position',
	'column' => 'position_code',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['users_position.employee_type_id'] = array(
	'f_id' => 8,
	'fg_id' => 7,
	'label' => 'Employee Type',
	'description' => '',
	'table' => 'users_position',
	'column' => 'employee_type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_employment_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'employment_type',
		'value' => 'employment_type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][7]['users_position.immediate_id'] = array(
	'f_id' => 7,
	'fg_id' => 7,
	'label' => 'Immediate Head',
	'description' => '',
	'table' => 'users_position',
	'column' => 'immediate_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'display_name',
		'value' => 'user_id',
		'textual_value_column' => ''
	)
);
$config['fields'][7]['users_position.immediate_position'] = array(
	'f_id' => 6,
	'fg_id' => 7,
	'label' => 'Immediate Position',
	'description' => '',
	'table' => 'users_position',
	'column' => 'immediate_position',
	'uitype_id' => 11,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['users_position.status_id'] = array(
	'f_id' => 9,
	'fg_id' => 7,
	'label' => 'Active',
	'description' => '',
	'table' => 'users_position',
	'column' => 'status_id',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['users_position.job_description'] = array(
	'f_id' => 10,
	'fg_id' => 7,
	'label' => 'Active',
	'description' => '',
	'table' => 'users_position',
	'column' => 'job_description',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['users_position.attachment'] = array(
	'f_id' => 11,
	'fg_id' => 7,
	'label' => 'Active',
	'description' => '',
	'table' => 'users_position',
	'column' => 'attachment',
	'uitype_id' => 8,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);