<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['users.login'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'User Login',
	'description' => '',
	'table' => 'users',
	'column' => 'login',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users.hash'] = array(
	'f_id' => 16,
	'fg_id' => 1,
	'label' => 'Password',
	'description' => '',
	'table' => 'users',
	'column' => 'hash',
	'uitype_id' => 7,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.company_id'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Company',
	'description' => '',
	'table' => 'users_profile',
	'column' => 'company_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_company',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'company',
		'value' => 'company_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['users.role_id'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Role',
	'description' => '',
	'table' => 'users',
	'column' => 'role_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'roles',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'role',
		'value' => 'role_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['users.active'] = array(
	'f_id' => 14,
	'fg_id' => 1,
	'label' => 'Active',
	'description' => '',
	'table' => 'users',
	'column' => 'active',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['users_profile.firstname'] = array(
	'f_id' => 8,
	'fg_id' => 2,
	'label' => 'Firstname',
	'description' => '',
	'table' => 'users_profile',
	'column' => 'firstname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['users_profile.lastname'] = array(
	'f_id' => 9,
	'fg_id' => 2,
	'label' => 'Lastname',
	'description' => '',
	'table' => 'users_profile',
	'column' => 'lastname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['users_profile.middlename'] = array(
	'f_id' => 11,
	'fg_id' => 2,
	'label' => 'Middlename',
	'description' => '',
	'table' => 'users_profile',
	'column' => 'middlename',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['users_profile.nickname'] = array(
	'f_id' => 15,
	'fg_id' => 2,
	'label' => 'Nickname',
	'description' => '',
	'table' => 'users_profile',
	'column' => 'nickname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['users_profile.photo'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Photo',
	'description' => '',
	'table' => 'users_profile',
	'column' => 'photo',
	'uitype_id' => 8,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['users.email'] = array(
	'f_id' => 13,
	'fg_id' => 3,
	'label' => 'Email',
	'description' => '',
	'table' => 'users',
	'column' => 'email',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required|valid_email',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.business_level_id'] = array(
	'f_id' => 14,
	'fg_id' => 1,
	'label' => 'Business Level',
	'description' => '',
	'table' => 'users_profile',
	'column' => 'business_level_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'business_level',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'level',
		'value' => 'level_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['users_profile.birth_date'] = array(
	'f_id' => 15,
	'fg_id' => 8,
	'label' => 'Birth Date',
	'description' => 'Birth Date',
	'table' => 'users_profile',
	'column' => 'birth_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][2]['users_profile.suffix'] = array(
	'f_id' => 16,
	'fg_id' => 2,
	'label' => 'Suffix',
	'description' => '',
	'table' => 'users_profile',
	'column' => 'suffix',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);