<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['payroll_leave_conversion.employment_type_id'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Employment Type',
	'description' => '',
	'table' => 'payroll_leave_conversion',
	'column' => 'employment_type_id',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_employment_type',
		'multiple' => 1,
		'group_by' => '',
		'label' => 'employment_type',
		'value' => 'employment_type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_leave_conversion.description'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Description',
	'description' => '',
	'table' => 'payroll_leave_conversion',
	'column' => 'description',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_leave_conversion.forfeited'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Forfeited',
	'description' => '',
	'table' => 'payroll_leave_conversion',
	'column' => 'forfeited',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_leave_conversion.convertible'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Covertible',
	'description' => '',
	'table' => 'payroll_leave_conversion',
	'column' => 'convertible',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_leave_conversion.carry_over'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Carry Over',
	'description' => '',
	'table' => 'payroll_leave_conversion',
	'column' => 'carry_over',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_leave_conversion.form_id'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Form Type',
	'description' => '',
	'table' => 'payroll_leave_conversion',
	'column' => 'form_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'time_form',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'form',
		'value' => 'form_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_leave_conversion.company_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Company',
	'description' => '',
	'table' => 'payroll_leave_conversion',
	'column' => 'company_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_company',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'company_code',
		'value' => 'company_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_leave_conversion.nontax'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Non-Taxable',
	'description' => '',
	'table' => 'payroll_leave_conversion',
	'column' => 'nontax',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_leave_conversion.taxable'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Taxable',
	'description' => '',
	'table' => 'payroll_leave_conversion',
	'column' => 'taxable',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
