<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][2]['partners_health_records.recommendation'] = array(
	'f_id' => 9,
	'fg_id' => 2,
	'label' => 'Recommendations',
	'description' => '',
	'table' => 'partners_health_records',
	'column' => 'recommendation',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_health_records.attachments'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Attachments',
	'description' => '',
	'table' => 'partners_health_records',
	'column' => 'attachments',
	'uitype_id' => 8,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_health_records.health_type_status_id'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Status',
	'description' => '',
	'table' => 'partners_health_records',
	'column' => 'health_type_status_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_health_type_status',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'health_type_status',
		'value' => 'health_type_status_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['partners_health_records.date_of_completion'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Date of Completion',
	'description' => '',
	'table' => 'partners_health_records',
	'column' => 'date_of_completion',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_health_records.health_provider'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Health Provider',
	'description' => '',
	'table' => 'partners_health_records',
	'column' => 'health_provider',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_health_records.health_type_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Form Type',
	'description' => '',
	'table' => 'partners_health_records',
	'column' => 'health_type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_health_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'health_type',
		'value' => 'health_type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['partners_health_records.partner_id'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Partner',
	'description' => '',
	'table' => 'partners_health_records',
	'column' => 'partner_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'alias',
		'value' => 'partner_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['partners_health_records.diagnosis'] = array(
	'f_id' => 8,
	'fg_id' => 2,
	'label' => 'Diagnosis',
	'description' => '',
	'table' => 'partners_health_records',
	'column' => 'diagnosis',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['partners_health_records.findings'] = array(
	'f_id' => 7,
	'fg_id' => 2,
	'label' => 'Findings',
	'description' => '',
	'table' => 'partners_health_records',
	'column' => 'findings',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
