<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['payroll_bank.description'] = array(
	'f_id' => 10,
	'fg_id' => 1,
	'label' => 'Description',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'description',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.address'] = array(
	'f_id' => 11,
	'fg_id' => 1,
	'label' => 'Address',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'address',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.signatory_2'] = array(
	'f_id' => 15,
	'fg_id' => 1,
	'label' => 'Signatory 2',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'signatory_2',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 15,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.signatory_1'] = array(
	'f_id' => 14,
	'fg_id' => 1,
	'label' => 'Signatory 1',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'signatory_1',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 14,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.branch_position'] = array(
	'f_id' => 13,
	'fg_id' => 1,
	'label' => 'Branch Position',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'branch_position',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 13,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.branch_officer'] = array(
	'f_id' => 12,
	'fg_id' => 1,
	'label' => 'Branch Officer',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'branch_officer',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 12,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.branch_code'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Branch Code',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'branch_code',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.ceiling_amount'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Ceiling Amount',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'ceiling_amount',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.batch_no'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Batch Number',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'batch_no',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.account_no'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Account Number',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'account_no',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.bank'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Account Name',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'bank',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.account_name'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Account Name',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'account_name',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.bank_code_alpha'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Bank Code Alpha',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'bank_code_alpha',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.bank_code_numeric'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Bank Code Numeric',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'bank_code_numeric',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_bank.bank_type'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Bank Type',
	'description' => '',
	'table' => 'payroll_bank',
	'column' => 'bank_type',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
