<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['performance_setup_performance.send_sms'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Send SMS',
	'description' => 'Send SMS',
	'table' => 'performance_setup_performance',
	'column' => 'send_sms',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_setup_performance.send_email'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Send Email',
	'description' => 'Send Email',
	'table' => 'performance_setup_performance',
	'column' => 'send_email',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_setup_performance.send_feeds'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Send Feeds Notification',
	'description' => 'Send Feeds Notification',
	'table' => 'performance_setup_performance',
	'column' => 'send_feeds',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_setup_performance.status_id'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Is Active',
	'description' => 'Is Active',
	'table' => 'performance_setup_performance',
	'column' => 'status_id',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_setup_performance.description'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Description',
	'description' => 'Description',
	'table' => 'performance_setup_performance',
	'column' => 'description',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_setup_performance.performance_group'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Performance Group',
	'description' => 'Performance Group',
	'table' => 'performance_setup_performance',
	'column' => 'performance_group',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_setup_performance.performance'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Performance',
	'description' => 'Performance',
	'table' => 'performance_setup_performance',
	'column' => 'performance',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
