<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['training_calendar.revalida_date'] = array(
	'f_id' => 24,
	'fg_id' => 1,
	'label' => 'Evaluation Date',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'revalida_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 22,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.planned'] = array(
	'f_id' => 23,
	'fg_id' => 1,
	'label' => 'Planned',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'planned',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 21,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.with_certification'] = array(
	'f_id' => 18,
	'fg_id' => 1,
	'label' => 'Certification',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'with_certification',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 17,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.training_revalida_master_id'] = array(
	'f_id' => 17,
	'fg_id' => 1,
	'label' => 'Level 2 and 3 Evaluation',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'training_revalida_master_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 16,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_revalida_master',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'revalida_type',
		'value' => 'training_revalida_master_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['training_calendar.publish_date'] = array(
	'f_id' => 16,
	'fg_id' => 1,
	'label' => 'Publish Date',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'publish_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 15,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.feedback_category_id'] = array(
	'f_id' => 15,
	'fg_id' => 1,
	'label' => 'Evaluation Form',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'feedback_category_id',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 14,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_feedback_category',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'feedback_category',
		'value' => 'feedback_category_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['training_calendar.last_registration_date'] = array(
	'f_id' => 14,
	'fg_id' => 1,
	'label' => 'Last Registration Date',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'last_registration_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 13,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.cost_per_pax'] = array(
	'f_id' => 13,
	'fg_id' => 1,
	'label' => 'Cost Per Pax',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'cost_per_pax',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 12,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.registration_date'] = array(
	'f_id' => 12,
	'fg_id' => 1,
	'label' => 'Registration Date',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'registration_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.topic'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Training Course Description',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'topic',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.venue'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Venue',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'venue',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.equipment'] = array(
	'f_id' => 11,
	'fg_id' => 1,
	'label' => 'Equipment',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'equipment',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.tba'] = array(
	'f_id' => 10,
	'fg_id' => 1,
	'label' => 'To Be Announce',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'tba',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.training_capacity'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Minimum Trainee Capacity',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'training_capacity',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.min_training_capacity'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Maximum Trainee Capacity',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'min_training_capacity',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.training_category_id'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Training Category',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'training_category_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.training_calendar_id'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Training Provider',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'training_calendar_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['training_calendar.calendar_type_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Training Type',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'calendar_type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_calendar_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'calendar_type',
		'value' => 'calendar_type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['training_calendar.course_id'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Training Course',
	'description' => '',
	'table' => 'training_calendar',
	'column' => 'course_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_course',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'course',
		'value' => 'course_id',
		'textual_value_column' => ''
	)
);
