<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['payroll_partners_loan.user_id'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Employee Name',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'user_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_loan.loan_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Loan Type',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'loan_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_loan',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'loan',
		'value' => 'loan_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners_loan.loan_status_id'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Loan Status',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'loan_status_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_loan_status',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'loan_status',
		'value' => 'loan_status_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners_loan.entry_date'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Entry Date',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'entry_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_loan.no_payments'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'No. of payments',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'no_payments',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required|integer',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_loan.releasing_debit_account_id'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Releasing Debit Account',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'releasing_debit_account_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_account',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'account_name',
		'value' => 'account_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners_loan.releasing_credit_account_id'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Releasing Credit Account',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'releasing_credit_account_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_account',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'account_name',
		'value' => 'account_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners_loan.week'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'week',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'week',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_week',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'week',
		'value' => 'week_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['payroll_partners_loan.loan_principal'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Loan Principal',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'loan_principal',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][1]['payroll_partners_loan.amount'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Amount',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'amount',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => 'required|numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][1]['payroll_partners_loan.interest'] = array(
	'f_id' => 10,
	'fg_id' => 1,
	'label' => 'Interest',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'interest',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => 'required|numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][1]['payroll_partners_loan.beginning_balance'] = array(
	'f_id' => 11,
	'fg_id' => 1,
	'label' => 'Beginning Balance',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'beginning_balance',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][1]['payroll_partners_loan.description'] = array(
	'f_id' => 12,
	'fg_id' => 1,
	'label' => 'Description',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'description',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 12,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_loan.remarks'] = array(
	'f_id' => 27,
	'fg_id' => 1,
	'label' => 'Remarks',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'remarks',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 13,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['payroll_partners_loan.start_date'] = array(
	'f_id' => 13,
	'fg_id' => 2,
	'label' => 'Start Date',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'start_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['payroll_partners_loan.payment_mode_id'] = array(
	'f_id' => 14,
	'fg_id' => 2,
	'label' => 'Payment Mode',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'payment_mode_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_payment_mode',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'payment_mode',
		'value' => 'payment_mode_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['payroll_partners_loan.no_payments_remaining'] = array(
	'f_id' => 15,
	'fg_id' => 2,
	'label' => 'Payments Remaining',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'no_payments_remaining',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required|integer',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['payroll_partners_loan.amortization_credit_account_id'] = array(
	'f_id' => 16,
	'fg_id' => 2,
	'label' => 'Amortization Credit ',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'amortization_credit_account_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_account',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'account_name',
		'value' => 'account_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['payroll_partners_loan.interest_credit_account_id'] = array(
	'f_id' => 17,
	'fg_id' => 2,
	'label' => 'Interest Credit ',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'interest_credit_account_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'payroll_account',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'account_name',
		'value' => 'account_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['payroll_partners_loan.running_balance'] = array(
	'f_id' => 18,
	'fg_id' => 2,
	'label' => 'Running Balance',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'running_balance',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][2]['payroll_partners_loan.system_amortization'] = array(
	'f_id' => 19,
	'fg_id' => 2,
	'label' => 'System Amortization',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'system_amortization',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][2]['payroll_partners_loan.system_interest'] = array(
	'f_id' => 20,
	'fg_id' => 2,
	'label' => 'System Interest',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'system_interest',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][2]['payroll_partners_loan.user_amortization'] = array(
	'f_id' => 21,
	'fg_id' => 2,
	'label' => 'User Amortization',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'user_amortization',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][2]['payroll_partners_loan.user_interest'] = array(
	'f_id' => 22,
	'fg_id' => 2,
	'label' => 'User Interest',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'user_interest',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][3]['payroll_partners_loan.last_payment_date'] = array(
	'f_id' => 23,
	'fg_id' => 3,
	'label' => 'Last Payment Date',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'last_payment_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'date',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['payroll_partners_loan.total_amount_paid'] = array(
	'f_id' => 24,
	'fg_id' => 3,
	'label' => 'Total Amount Paid',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'total_amount_paid',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
$config['fields'][3]['payroll_partners_loan.no_payments_paid'] = array(
	'f_id' => 25,
	'fg_id' => 3,
	'label' => 'Total No. of Payments',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'no_payments_paid',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['payroll_partners_loan.total_arrears'] = array(
	'f_id' => 26,
	'fg_id' => 3,
	'label' => 'Total Arrears',
	'description' => '',
	'table' => 'payroll_partners_loan',
	'column' => 'total_arrears',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'numeric',
	'active' => '1',
	'encrypt' => 1
);
