<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['performance_planning.employment_status_id'] = array(
	'f_id' => 13,
	'fg_id' => 1,
	'label' => 'Employment Status Filter',
	'description' => 'Employment Status Filter',
	'table' => 'performance_planning',
	'column' => 'employment_status_id',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_employment_status',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'employment_status',
		'value' => 'employment_status_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['performance_planning.filter_by'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Filter By',
	'description' => 'Filter By',
	'table' => 'performance_planning',
	'column' => 'filter_by',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'performance_planning_filter',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'filter_by',
		'value' => 'filter_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['performance_planning_applicable.user_id'] = array(
	'f_id' => 12,
	'fg_id' => 1,
	'label' => 'Applicable For',
	'description' => 'Applicable For',
	'table' => 'performance_planning_applicable',
	'column' => 'user_id',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'full_name',
		'value' => 'user_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['performance_planning.filter_id'] = array(
	'f_id' => 11,
	'fg_id' => 1,
	'label' => 'Selection',
	'description' => 'Selection',
	'table' => 'performance_planning',
	'column' => 'filter_id',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_company',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'company',
		'value' => 'company_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['performance_planning.notes'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Notes',
	'description' => 'Notes',
	'table' => 'performance_planning',
	'column' => 'notes',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_planning.status_id'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Period Status',
	'description' => 'Period Status',
	'table' => 'performance_planning',
	'column' => 'status_id',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_planning.template_id'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Template',
	'description' => 'Template',
	'table' => 'performance_planning',
	'column' => 'template_id',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'performance_template',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'template',
		'value' => 'template_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['performance_planning.performance_type_id'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Performance Type',
	'description' => 'Performance Type',
	'table' => 'performance_planning',
	'column' => 'performance_type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'performance_setup_performance',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'performance',
		'value' => 'performance_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['performance_planning.date_to'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Date To',
	'description' => 'Date To',
	'table' => 'performance_planning',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_planning.date_from'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Date From',
	'description' => 'Date From',
	'table' => 'performance_planning',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['performance_planning.year'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Year',
	'description' => 'Year`',
	'table' => 'performance_planning',
	'column' => 'year',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
