<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][3]['partners.orig_hired_date'] = array(
	'f_id' => 18,
	'fg_id' => 3,
	'label' => 'Original Date Hired',
	'description' => 'Original Date Hired',
	'table' => 'partners',
	'column' => 'orig_hired_date',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.nickname'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Nick Name',
	'description' => 'Nick Name',
	'table' => 'users_profile',
	'column' => 'nickname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.maidenname'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Maiden Name',
	'description' => 'Maiden Name',
	'table' => 'users_profile',
	'column' => 'maidenname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.middleinitial'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Middle Initial',
	'description' => 'Middle Initial',
	'table' => 'users_profile',
	'column' => 'middleinitial',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.middlename'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Middle Name',
	'description' => 'Middle Name',
	'table' => 'users_profile',
	'column' => 'middlename',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.firstname'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'First Name',
	'description' => 'First Name',
	'table' => 'users_profile',
	'column' => 'firstname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.lastname'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Last Name',
	'description' => 'Last Name',
	'table' => 'users_profile',
	'column' => 'lastname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['partners.effectivity_date'] = array(
	'f_id' => 17,
	'fg_id' => 3,
	'label' => 'Date Hired',
	'description' => 'Date Hired',
	'table' => 'partners',
	'column' => 'effectivity_date',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['partners.status_id'] = array(
	'f_id' => 16,
	'fg_id' => 3,
	'label' => 'Employee Status',
	'description' => 'Employee Status',
	'table' => 'partners',
	'column' => 'status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['partners.shift_id'] = array(
	'f_id' => 15,
	'fg_id' => 2,
	'label' => 'Work Schedule',
	'description' => 'Work Schedule',
	'table' => 'partners',
	'column' => 'shift_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['partners.biometric'] = array(
	'f_id' => 14,
	'fg_id' => 2,
	'label' => 'Biometric Number',
	'description' => 'Biometric Number',
	'table' => 'partners',
	'column' => 'biometric',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['partners.id_number'] = array(
	'f_id' => 13,
	'fg_id' => 2,
	'label' => 'ID Number',
	'description' => 'ID Number',
	'table' => 'partners',
	'column' => 'id_number',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['users_profile.role_id'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Role',
	'description' => 'Role',
	'table' => 'users_profile',
	'column' => 'role_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['users_profile.position_id'] = array(
	'f_id' => 11,
	'fg_id' => 2,
	'label' => 'Position Title',
	'description' => 'Position Title',
	'table' => 'users_profile',
	'column' => 'position_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['users_profile.location_id'] = array(
	'f_id' => 10,
	'fg_id' => 2,
	'label' => 'Location',
	'description' => 'Location',
	'table' => 'users_profile',
	'column' => 'location_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['users_profile.company'] = array(
	'f_id' => 9,
	'fg_id' => 2,
	'label' => 'Company',
	'description' => 'Company',
	'table' => 'users_profile',
	'column' => 'company',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
