<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['time_forms.date_from'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['time_forms.date_to'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['time_forms.reason'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['time_forms_upload.upload_id'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['time_forms.form_status_id'] = array(
	'f_id' => 67,
	'fg_id' => 1,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_forms.date_from'] = array(
	'f_id' => 5,
	'fg_id' => 2,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_forms.date_to'] = array(
	'f_id' => 6,
	'fg_id' => 2,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_forms.reason'] = array(
	'f_id' => 7,
	'fg_id' => 2,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_forms_upload.upload_id'] = array(
	'f_id' => 8,
	'fg_id' => 2,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_forms.form_status_id'] = array(
	'f_id' => 68,
	'fg_id' => 2,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['time_forms.date_from'] = array(
	'f_id' => 9,
	'fg_id' => 3,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['time_forms.date_to'] = array(
	'f_id' => 10,
	'fg_id' => 3,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['time_forms.reason'] = array(
	'f_id' => 11,
	'fg_id' => 3,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['time_forms_upload.upload_id'] = array(
	'f_id' => 12,
	'fg_id' => 3,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['time_forms.form_status_id'] = array(
	'f_id' => 69,
	'fg_id' => 3,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['time_forms.date_from'] = array(
	'f_id' => 13,
	'fg_id' => 4,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['time_forms.date_to'] = array(
	'f_id' => 14,
	'fg_id' => 4,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['time_forms.reason'] = array(
	'f_id' => 15,
	'fg_id' => 4,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['time_forms_upload.upload_id'] = array(
	'f_id' => 16,
	'fg_id' => 4,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['time_forms.form_status_id'] = array(
	'f_id' => 70,
	'fg_id' => 4,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms.date_from'] = array(
	'f_id' => 17,
	'fg_id' => 5,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms.date_to'] = array(
	'f_id' => 18,
	'fg_id' => 5,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms.reason'] = array(
	'f_id' => 19,
	'fg_id' => 5,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms_upload.upload_id'] = array(
	'f_id' => 20,
	'fg_id' => 5,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms_maternity.delivery_id'] = array(
	'f_id' => 21,
	'fg_id' => 5,
	'label' => 'Delivery',
	'description' => 'Delivery',
	'table' => 'time_forms_maternity',
	'column' => 'delivery_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms_maternity.pregnancy_no'] = array(
	'f_id' => 22,
	'fg_id' => 5,
	'label' => 'No. of Pregnancy',
	'description' => 'No. of Pregnancy',
	'table' => 'time_forms_maternity',
	'column' => 'pregnancy_no',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms_maternity.expected_date'] = array(
	'f_id' => 23,
	'fg_id' => 5,
	'label' => 'Expected Delivery',
	'description' => 'Expected Delivery',
	'table' => 'time_forms_maternity',
	'column' => 'expected_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms_maternity.actual_date'] = array(
	'f_id' => 24,
	'fg_id' => 5,
	'label' => 'Actual Delivery',
	'description' => 'Actual Delivery',
	'table' => 'time_forms_maternity',
	'column' => 'actual_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms_maternity.return_date'] = array(
	'f_id' => 25,
	'fg_id' => 5,
	'label' => 'Report Date',
	'description' => 'Report Date',
	'table' => 'time_forms_maternity',
	'column' => 'return_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['time_forms.form_status_id'] = array(
	'f_id' => 70,
	'fg_id' => 5,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['time_forms.date_from'] = array(
	'f_id' => 26,
	'fg_id' => 6,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['time_forms.date_to'] = array(
	'f_id' => 27,
	'fg_id' => 6,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['time_forms.reason'] = array(
	'f_id' => 28,
	'fg_id' => 6,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['time_forms_upload.upload_id'] = array(
	'f_id' => 29,
	'fg_id' => 6,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['time_forms_maternity.actual_date'] = array(
	'f_id' => 30,
	'fg_id' => 6,
	'label' => 'Actual Delivery',
	'description' => 'Actual Delivery',
	'table' => 'time_forms_maternity',
	'column' => 'actual_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['time_forms.form_status_id'] = array(
	'f_id' => 71,
	'fg_id' => 6,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['time_forms.date_from'] = array(
	'f_id' => 31,
	'fg_id' => 7,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['time_forms.date_to'] = array(
	'f_id' => 32,
	'fg_id' => 7,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['time_forms.reason'] = array(
	'f_id' => 33,
	'fg_id' => 7,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['time_forms_upload.upload_id'] = array(
	'f_id' => 34,
	'fg_id' => 7,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][7]['time_forms.form_status_id'] = array(
	'f_id' => 72,
	'fg_id' => 7,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][13]['time_forms.date_from'] = array(
	'f_id' => 35,
	'fg_id' => 13,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][13]['time_forms.date_to'] = array(
	'f_id' => 36,
	'fg_id' => 13,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][13]['time_forms.reason'] = array(
	'f_id' => 37,
	'fg_id' => 13,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][13]['time_forms_upload.upload_id'] = array(
	'f_id' => 38,
	'fg_id' => 13,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][13]['time_forms.form_status_id'] = array(
	'f_id' => 78,
	'fg_id' => 13,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][14]['time_forms.date_from'] = array(
	'f_id' => 39,
	'fg_id' => 14,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][14]['time_forms.date_to'] = array(
	'f_id' => 40,
	'fg_id' => 14,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][14]['time_forms.reason'] = array(
	'f_id' => 41,
	'fg_id' => 14,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][14]['time_forms_upload.upload_id'] = array(
	'f_id' => 42,
	'fg_id' => 14,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][14]['time_forms.form_status_id'] = array(
	'f_id' => 79,
	'fg_id' => 14,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms.date_from'] = array(
	'f_id' => 43,
	'fg_id' => 8,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 16,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms.date_to'] = array(
	'f_id' => 44,
	'fg_id' => 8,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 16,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms.reason'] = array(
	'f_id' => 45,
	'fg_id' => 8,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms_upload.upload_id'] = array(
	'f_id' => 45,
	'fg_id' => 8,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms_obt.location'] = array(
	'f_id' => 46,
	'fg_id' => 8,
	'label' => 'Location',
	'description' => 'Location',
	'table' => 'time_forms_obt',
	'column' => 'location',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms_obt.company_to_visit'] = array(
	'f_id' => 47,
	'fg_id' => 8,
	'label' => 'Company Name',
	'description' => 'Company Name',
	'table' => 'time_forms_obt',
	'column' => 'company_to_visit',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms_obt.name'] = array(
	'f_id' => 48,
	'fg_id' => 8,
	'label' => 'Contact Person',
	'description' => 'Contact Person',
	'table' => 'time_forms_obt',
	'column' => 'name',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms_obt.position'] = array(
	'f_id' => 49,
	'fg_id' => 8,
	'label' => 'Position Title',
	'description' => 'Position Title',
	'table' => 'time_forms_obt',
	'column' => 'position',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms_obt.contact_no'] = array(
	'f_id' => 50,
	'fg_id' => 8,
	'label' => 'Contact Number',
	'description' => 'Contact Number',
	'table' => 'time_forms_obt',
	'column' => 'contact_no',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][8]['time_forms.form_status_id'] = array(
	'f_id' => 73,
	'fg_id' => 8,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][9]['time_forms.date_from'] = array(
	'f_id' => 51,
	'fg_id' => 9,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 16,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][9]['time_forms.date_to'] = array(
	'f_id' => 52,
	'fg_id' => 9,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 16,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][9]['time_forms.reason'] = array(
	'f_id' => 53,
	'fg_id' => 9,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][9]['time_forms_upload.upload_id'] = array(
	'f_id' => 54,
	'fg_id' => 9,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][9]['time_forms.form_status_id'] = array(
	'f_id' => 74,
	'fg_id' => 9,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][10]['time_forms.date_from'] = array(
	'f_id' => 55,
	'fg_id' => 10,
	'label' => 'Date',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][10]['time_forms.date_to'] = array(
	'f_id' => 56,
	'fg_id' => 10,
	'label' => 'Time',
	'description' => 'Time',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][10]['time_forms.reason'] = array(
	'f_id' => 57,
	'fg_id' => 10,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][10]['time_forms_upload.upload_id'] = array(
	'f_id' => 58,
	'fg_id' => 10,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][10]['time_forms.form_status_id'] = array(
	'f_id' => 75,
	'fg_id' => 10,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][11]['time_forms.date_from'] = array(
	'f_id' => 59,
	'fg_id' => 11,
	'label' => 'In',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 16,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][11]['time_forms.date_to'] = array(
	'f_id' => 60,
	'fg_id' => 11,
	'label' => 'Out',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 16,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][11]['time_forms.reason'] = array(
	'f_id' => 61,
	'fg_id' => 11,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][11]['time_forms_upload.upload_id'] = array(
	'f_id' => 62,
	'fg_id' => 11,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][11]['time_forms.form_status_id'] = array(
	'f_id' => 76,
	'fg_id' => 11,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][12]['time_forms.date_from'] = array(
	'f_id' => 63,
	'fg_id' => 12,
	'label' => 'Date',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][12]['time_forms.date_to'] = array(
	'f_id' => 64,
	'fg_id' => 12,
	'label' => 'Date',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][12]['time_forms.reason'] = array(
	'f_id' => 65,
	'fg_id' => 12,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][12]['time_forms_upload.upload_id'] = array(
	'f_id' => 66,
	'fg_id' => 12,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][12]['time_forms_date.shift_id'] = array(
	'f_id' => 66,
	'fg_id' => 12,
	'label' => 'Current Schedule',
	'description' => 'Current Schedule',
	'table' => 'time_forms_date',
	'column' => 'shift_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][12]['time_forms_date.shift_to'] = array(
	'f_id' => 66,
	'fg_id' => 12,
	'label' => 'New Schedule',
	'description' => 'New Schedule',
	'table' => 'time_forms_date',
	'column' => 'shift_to',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][12]['time_forms.form_status_id'] = array(
	'f_id' => 77,
	'fg_id' => 12,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][15]['time_forms.date_from'] = array(
	'f_id' => 55,
	'fg_id' => 10,
	'label' => 'Date',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][15]['time_forms.date_to'] = array(
	'f_id' => 56,
	'fg_id' => 10,
	'label' => 'Time',
	'description' => 'Time',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][15]['time_forms.reason'] = array(
	'f_id' => 57,
	'fg_id' => 10,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][15]['time_forms_upload.upload_id'] = array(
	'f_id' => 58,
	'fg_id' => 10,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][15]['time_forms.form_status_id'] = array(
	'f_id' => 75,
	'fg_id' => 10,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][16]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 16,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][16]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 16,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][16]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 16,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][16]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 16,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][16]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 16,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][17]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 17,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][17]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 17,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][17]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 17,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][17]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 17,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][17]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 17,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][18]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 18,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][18]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 18,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][18]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 18,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][18]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 18,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][18]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 18,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][19]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 19,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][19]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 19,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][19]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 19,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][19]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 19,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][19]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 19,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][20]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 20,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][20]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 20,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][20]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 20,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][20]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 20,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][20]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 20,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][21]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 21,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][21]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 21,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][21]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 21,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][21]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 21,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][21]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 21,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][22]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 22,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][22]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 22,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][22]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 22,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][22]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 22,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][22]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 22,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][23]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 23,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][23]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 23,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][23]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 23,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][23]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 23,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][23]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 23,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][24]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 24,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][24]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 24,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][24]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 24,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][24]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 24,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][24]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 24,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][25]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 25,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][25]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 25,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][25]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 25,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][25]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 25,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][25]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 25,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][26]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 26,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][26]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 26,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][26]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 26,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][26]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 26,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][26]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 26,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);


$config['fields'][27]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 27,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][27]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 27,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][27]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 27,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][27]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 27,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][27]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 27,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);


$config['fields'][28]['time_forms.date_from'] = array(
	'f_id' => 80,
	'fg_id' => 28,
	'label' => 'From',
	'description' => 'Date From',
	'table' => 'time_forms',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][28]['time_forms.date_to'] = array(
	'f_id' => 81,
	'fg_id' => 28,
	'label' => 'To',
	'description' => 'Date To',
	'table' => 'time_forms',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][28]['time_forms.reason'] = array(
	'f_id' => 82,
	'fg_id' => 28,
	'label' => 'Reason',
	'description' => 'Reason',
	'table' => 'time_forms',
	'column' => 'reason',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][28]['time_forms_upload.upload_id'] = array(
	'f_id' => 83,
	'fg_id' => 28,
	'label' => 'File Upload',
	'description' => 'File Upload',
	'table' => 'time_forms_upload',
	'column' => 'upload_id',
	'uitype_id' => 9,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][28]['time_forms.form_status_id'] = array(
	'f_id' => 84,
	'fg_id' => 28,
	'label' => 'Status',
	'description' => 'Form Status',
	'table' => 'time_forms',
	'column' => 'form_status_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);

if(get_time_form_id('ADDL') != false){

	$config['fields'][get_time_form_id('ADDL')]['time_forms.date_from'] = array(
		'f_id' => 90,
		'fg_id' => get_time_form_id('ADDL'),
		'label' => 'From',
		'description' => 'Date From',
		'table' => 'time_forms',
		'column' => 'date_from',
		'uitype_id' => 16,
		'display_id' => 3,
		'quick_edit' => 1,
		'sequence' => 1,
		'datatype' => 'required',
		'active' => '1',
		'encrypt' => 0
	);
	$config['fields'][get_time_form_id('ADDL')]['time_forms.date_to'] = array(
		'f_id' => 90,
		'fg_id' => get_time_form_id('ADDL'),
		'label' => 'To',
		'description' => 'Date To',
		'table' => 'time_forms',
		'column' => 'date_to',
		'uitype_id' => 16,
		'display_id' => 3,
		'quick_edit' => 1,
		'sequence' => 3,
		'datatype' => 'required',
		'active' => '1',
		'encrypt' => 0
	);
	$config['fields'][get_time_form_id('ADDL')]['time_forms.reason'] = array(
		'f_id' => 91,
		'fg_id' => get_time_form_id('ADDL'),
		'label' => 'Reason',
		'description' => 'Reason',
		'table' => 'time_forms',
		'column' => 'reason',
		'uitype_id' => 2,
		'display_id' => 3,
		'quick_edit' => 1,
		'sequence' => 4,
		'datatype' => 'required',
		'active' => '1',
		'encrypt' => 0
	);
	$config['fields'][get_time_form_id('ADDL')]['time_forms_upload.upload_id'] = array(
		'f_id' => 92,
		'fg_id' => get_time_form_id('ADDL'),
		'label' => 'File Upload',
		'description' => 'File Upload',
		'table' => 'time_forms_upload',
		'column' => 'upload_id',
		'uitype_id' => 9,
		'display_id' => 3,
		'quick_edit' => 1,
		'sequence' => 5,
		'datatype' => 'V',
		'active' => '1',
		'encrypt' => 0
	);
	$config['fields'][get_time_form_id('ADDL')]['time_forms.form_status_id'] = array(
		'f_id' => 93,
		'fg_id' => get_time_form_id('ADDL'),
		'label' => 'Status',
		'description' => 'Form Status',
		'table' => 'time_forms',
		'column' => 'form_status_id',
		'uitype_id' => 1,
		'display_id' => 3,
		'quick_edit' => 1,
		'sequence' => 1,
		'datatype' => 'V',
		'active' => '1',
		'encrypt' => 0
	);
}