<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
$config["edit_cached_query"] = 'SELECT `ww_recruitment_request`.`request_id` as record_id, 
`ww_recruitment_request`.`document_no` as document_no, 
`ww_recruitment_request`.`created_on` as "recruitment_request.created_on",
`ww_recruitment_request`.`position_id` as "recruitment_request.position_id",
`ww_recruitment_request`.`replacement_of` as "recruitment_request.replacement_of", 
`ww_recruitment_request`.`due_to_id` as "recruitment_request.due_to_id", 
`ww_recruitment_request`.`replacement_transfer_location` as "recruitment_request.replacement_transfer_location", 
`ww_recruitment_request`.`replacement_transfer_leave_date_from` as "recruitment_request.replacement_transfer_leave_date_from", 
`ww_recruitment_request`.`replacement_transfer_leave_date_to` as "recruitment_request.replacement_transfer_leave_date_to", 
`ww_recruitment_request`.`age_range_from` as "recruitment_request.age_range_from",
`ww_recruitment_request`.`age_range_to` as "recruitment_request.age_range_to",
`ww_recruitment_request`.`gender` as "recruitment_request.gender",
`ww_recruitment_request`.`civil_status_id` as "recruitment_request.civil_status_id",
`ww_recruitment_request`.`max_no_personel` as "recruitment_request.max_no_personel",
`ww_recruitment_request`.`total_no_incumbent` as "recruitment_request.total_no_incumbent",
`ww_recruitment_request`.`educational_attainment` as "recruitment_request.educational_attainment",
`ww_recruitment_request`.`user_id` as "recruitment_request.user_id", 
`ww_recruitment_request`.`status_id` as "recruitment_request.status_id", 
`ww_recruitment_request`.`nature_id` as "recruitment_request.nature_id", 
`ww_recruitment_request`.`job_class_id` as "recruitment_request.job_class_id", 
`ww_recruitment_request`.`employment_status_id` as "recruitment_request.employment_status_id", 
`ww_recruitment_request`.`budgeted` as "recruitment_request.budgeted", 
`ww_recruitment_request`.`hiring_type` as "recruitment_request.hiring_type", 
`ww_recruitment_request`.`quantity` as "recruitment_request.quantity",
`ww_recruitment_request`.`contract_duration` as "recruitment_request.contract_duration",
`ww_recruitment_request`.`attachment` as "recruitment_request.attachment",
`ww_recruitment_request`.`hr_remarks` as "recruitment_request.hr_remarks",
`ww_recruitment_request`.`closing_remarks` as "recruitment_request.closing_remarks",
`ww_recruitment_request`.`closed_by` as "recruitment_request.closed_by",
`ww_recruitment_request`.`hr_assigned` as "recruitment_request.hr_assigned",
DATE_FORMAT(ww_recruitment_request.delivery_date, \'%M %d, %Y\')  as "recruitment_request.delivery_date",
`ww_recruitment_request`.`modified_on` as "recruitment_request.modified_on", 
`ww_recruitment_request`.`modified_by` as "recruitment_request.modified_by", 
ww_recruitment_request.created_by as "recruitment_request.created_by", 
DATE_FORMAT(ww_recruitment_request.created_on, \'%M %d, %Y\') as "recruitment_request.created_on", 
ww_recruitment_request.description as "recruitment_request.description", 
DATE_FORMAT(ww_recruitment_request.date_needed, \'%M %d, %Y\') as "recruitment_request.date_needed", 
ww_recruitment_request.hr_remarks_by as "recruitment_request.hr_remarks_by", 
DATE_FORMAT(ww_recruitment_request.hr_remarks_on, \'%M %d, %Y\ - %r\') as "recruitment_request.hr_remarks_on", 
ww_recruitment_request.department_id as "recruitment_request.department_id", 
ww_recruitment_request.company_id as "recruitment_request.company_id",
ww_recruitment_request.salary_from as "recruitment_request.salary_from", 
ww_recruitment_request.salary_to as "recruitment_request.salary_to",
ww_recruitment_request.budget_from as "recruitment_request.budget_from", 
ww_recruitment_request.budget_to as "recruitment_request.budget_to"
FROM (`ww_recruitment_request`)

WHERE `ww_recruitment_request`.`request_id` = "{$record_id}"';