<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][5]['users_profile.department_id'] = array(
	'f_id' => 9,
	'fg_id' => 5,
	'label' => 'Department',
	'description' => 'Department',
	'table' => 'users_profile',
	'column' => 'department_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_department',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'department',
		'value' => 'department_id',
		'textual_value_column' => ''
	)
);
$config['fields'][8]['users_profile.birth_date'] = array(
	'f_id' => 8,
	'fg_id' => 8,
	'label' => 'Birthday',
	'description' => 'Birthday',
	'table' => 'users_profile',
	'column' => 'birth_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][5]['users_profile.group_id'] = array(
	'f_id' => 7,
	'fg_id' => 5,
	'label' => 'Group',
	'description' => 'Group',
	'table' => 'users_profile',
	'column' => 'group_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_group',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'group',
		'value' => 'group_id',
		'textual_value_column' => ''
	)
);
$config['fields'][5]['users_profile.division_id'] = array(
	'f_id' => 6,
	'fg_id' => 5,
	'label' => 'Division',
	'description' => 'Division',
	'table' => 'users_profile',
	'column' => 'division_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_division',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'division',
		'value' => 'division_id',
		'textual_value_column' => ''
	)
);
$config['fields'][5]['users_department.immediate_id'] = array(
	'f_id' => 5,
	'fg_id' => 5,
	'label' => 'Reports To',
	'description' => '',
	'table' => 'users_department',
	'column' => 'immediate_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'display_name',
		'value' => 'user_id',
		'textual_value_column' => ''
	)
);
$config['fields'][3]['partners.effectivity_date'] = array(
	'f_id' => 17,
	'fg_id' => 3,
	'label' => 'Date Hired',
	'description' => 'Date Hired',
	'table' => 'partners',
	'column' => 'effectivity_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['partners.regularization_date'] = array(
	'f_id' => 17,
	'fg_id' => 3,
	'label' => 'Regularization Date',
	'description' => 'Regularization Date',
	'table' => 'partners',
	'column' => 'regularization_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['partners.status_id'] = array(
	'f_id' => 16,
	'fg_id' => 3,
	'label' => 'Employee Status',
	'description' => 'Employee Status',
	'table' => 'partners',
	'column' => 'status_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_employment_status',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'employment_status',
		'value' => 'employment_status_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['users_profile.location_id'] = array(
	'f_id' => 10,
	'fg_id' => 2,
	'label' => 'Location',
	'description' => 'Location',
	'table' => 'users_profile',
	'column' => 'location_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_location',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'location',
		'value' => 'location_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['users_profile.company'] = array(
	'f_id' => 9,
	'fg_id' => 2,
	'label' => 'Company',
	'description' => 'Company',
	'table' => 'users_profile',
	'column' => 'company',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_company',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'company',
		'value' => 'company_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['users_profile.position_id'] = array(
	'f_id' => 11,
	'fg_id' => 2,
	'label' => 'Position Title',
	'description' => 'Position Title',
	'table' => 'users_profile',
	'column' => 'position_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_position',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'position',
		'value' => 'position_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['partners.shift_id'] = array(
	'f_id' => 15,
	'fg_id' => 2,
	'label' => 'Work Schedule',
	'description' => 'Work Schedule',
	'table' => 'partners',
	'column' => 'shift_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'time_shift',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'shift',
		'value' => 'shift_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['partners.calendar_id'] = array(
	'f_id' => 15,
	'fg_id' => 2,
	'label' => 'Work Schedule',
	'description' => 'Work Schedule',
	'table' => 'partners',
	'column' => 'calendar_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'time_shift_weekly',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'calendar',
		'value' => 'calendar_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['users.role_id'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Role',
	'description' => 'Role',
	'table' => 'users',
	'column' => 'role_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'roles',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'role',
		'value' => 'role_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['partners.biometric'] = array(
	'f_id' => 14,
	'fg_id' => 2,
	'label' => 'Biometric Number',
	'description' => 'Biometric Number',
	'table' => 'partners',
	'column' => 'biometric',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['partners.id_number'] = array(
	'f_id' => 13,
	'fg_id' => 2,
	'label' => 'ID Number',
	'description' => 'ID Number',
	'table' => 'partners',
	'column' => 'id_number',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['users.email'] = array(
	'f_id' => 3,
	'fg_id' => 4,
	'label' => 'Email Address',
	'description' => 'Email Address',
	'table' => 'users',
	'column' => 'email',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.nickname'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Nick Name',
	'description' => 'Nick Name',
	'table' => 'users_profile',
	'column' => 'nickname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.maidenname'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Maiden Name',
	'description' => 'Maiden Name',
	'table' => 'users_profile',
	'column' => 'maidenname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.middlename'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Middle Name',
	'description' => 'Middle Name',
	'table' => 'users_profile',
	'column' => 'middlename',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.firstname'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'First Name',
	'description' => 'First Name',
	'table' => 'users_profile',
	'column' => 'firstname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['users_profile.lastname'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Last Name',
	'description' => 'Last Name',
	'table' => 'users_profile',
	'column' => 'lastname',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][3]['partners.employment_type_id'] = array(
	'f_id' => 18,
	'fg_id' => 3,
	'label' => 'Employee Type',
	'description' => 'Employee Type',
	'table' => 'partners',
	'column' => 'employment_type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_employment_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'employment_type',
		'value' => 'employment_type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][3]['partners.job_grade_id'] = array(
	'f_id' => 18,
	'fg_id' => 3,
	'label' => 'Job Grade',
	'description' => 'Job Grade',
	'table' => 'partners',
	'column' => 'job_grade_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_job_grade_level',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'job_level',
		'value' => 'job_grade_id',
		'textual_value_column' => ''
	)
);
$config['fields'][3]['partners.classification_id'] = array(
	'f_id' => 18,
	'fg_id' => 3,
	'label' => 'Classification',
	'description' => 'Classification',
	'table' => 'partners',
	'column' => 'classification_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'V',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_employment_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'classification',
		'value' => 'classification_id',
		'textual_value_column' => ''
	)
);
