<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['menu.label'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Label',
	'description' => '',
	'table' => 'menu',
	'column' => 'label',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['menu.icon'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Icon',
	'description' => '',
	'table' => 'menu',
	'column' => 'icon',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['menu.parent_menu_item_id'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Parent Menu',
	'description' => '',
	'table' => 'menu',
	'column' => 'parent_menu_item_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'menu',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'label',
		'value' => 'menu_item_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['menu.menu_item_type_id'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Menu Type',
	'description' => '',
	'table' => 'menu',
	'column' => 'menu_item_type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'menu_item_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'menu_item_type',
		'value' => 'menu_item_type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['menu.mod_id'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Module',
	'description' => '',
	'table' => 'menu',
	'column' => 'mod_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'modules',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'short_name',
		'value' => 'mod_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['menu.method'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Method',
	'description' => 'specific method of a module if menu is module type',
	'table' => 'menu',
	'column' => 'method',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['menu.uri'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'URL',
	'description' => 'if menu type is external, provide URL',
	'table' => 'menu',
	'column' => 'uri',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['menu.description'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Description',
	'description' => '',
	'table' => 'menu',
	'column' => 'description',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);