<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['partners_safe_manhour.medication_qty'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Medication Quantity',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'medication_qty',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_safe_manhour.attachment'] = array(
	'f_id' => 11,
	'fg_id' => 1,
	'label' => 'Attachments',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'attachment',
	'uitype_id' => 8,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_safe_manhour.details'] = array(
	'f_id' => 10,
	'fg_id' => 1,
	'label' => 'Details',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'details',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_safe_manhour.medication'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Medication ',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'medication',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_safe_manhour.status_id'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Status ',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'status_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_safe_manhour_status',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'status',
		'value' => 'status_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['partners_safe_manhour.date_return_to_work'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Date of Return to Work',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'date_return_to_work',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_safe_manhour.date_incident'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Date of Incident',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'date_incident',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_safe_manhour.total_manhour'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Total Manhour',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'total_manhour',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_safe_manhour.health_provider'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Health Provider',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'health_provider',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_safe_manhour.nature_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Nature ',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'nature_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_safe_manhour_nature',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'nature',
		'value' => 'nature_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['partners_safe_manhour.partner_id'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Partner',
	'description' => '',
	'table' => 'partners_safe_manhour',
	'column' => 'partner_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'alias',
		'value' => 'partner_id',
		'textual_value_column' => ''
	)
);
