<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();

$config['fields'][1]['recruitment_request.hiring_type'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Position',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'hiring_type',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_position',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'position',
		'value' => 'position_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['recruitment_request.user_id'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Requested By',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'user_id',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.description'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Description',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'description',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.date_needed'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Date Needed',
	'description' => 'Period Start Date ',
	'table' => 'recruitment_request',
	'column' => 'date_needed',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.position_id'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Position',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'position_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_position',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'position',
		'value' => 'position_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['recruitment_request.replacement_of'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Replacement Of',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'replacement_of',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'full_name',
		'value' => 'user_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['recruitment_request.department_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Department',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'department_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_department',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'department',
		'value' => 'department_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['recruitment_request.company_id'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Company',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'company_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_company',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'company',
		'value' => 'company_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['recruitment_request.nature_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Nature of Request',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'nature_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'recruitment_request_nature',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'nature',
		'value' => 'nature_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['recruitment_request.budgeted'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Nature of Request',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'budgeted',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
	// 'searchable' => array(
	// 	'type_id' => '1',
	// 	'table' => 'recruitment_request_nature',
	// 	'multiple' => 0,
	// 	'group_by' => '',
	// 	'label' => 'nature',
	// 	'value' => 'ww_recruitment_request_nature',
	// 	'textual_value_column' => ''
	// )
);
$config['fields'][1]['recruitment_request.job_class_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Job Class',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'job_class_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'user_job_class',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'job_class',
		'value' => 'job_class_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['recruitment_request.employment_status_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Employment Status',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'employment_status_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_employment_status',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'employment_status',
		'value' => 'employment_status_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['recruitment_request.attachment'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Attachment',
	'description' => 'Attachment',
	'table' => 'recruitment_request',
	'column' => 'attachment',
	'uitype_id' => 8,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][2]['recruitment_request.contract_duration'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Contract Duration',
	'description' => 'Contract Duration',
	'table' => 'recruitment_request',
	'column' => 'contract_duration',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.delivery_date'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Delivery Date',
	'description' => 'Delivery Date ',
	'table' => 'recruitment_request',
	'column' => 'delivery_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.hr_remarks'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'HR Remarks',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'hr_remarks',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.hr_assigned'] = array(
    'f_id' => 8,
    'fg_id' => 1,
    'label' => 'HR Assign',
    'description' => '',
    'table' => 'recruitment_request',
    'column' => 'hr_assigned',
    'uitype_id' => 2,
    'display_id' => 3,
    'quick_edit' => 1,
    'sequence' => 8,
    'datatype' => '',
    'active' => '1',
    'encrypt' => 0
);
$config['fields'][1]['recruitment_request.hr_remarks_by'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Requested By',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'hr_remarks_by',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.hr_remarks_on'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Requested on',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'hr_remarks_on',
	'uitype_id' => 16,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][2]['recruitment_request.salary_from'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Salary From',
	'description' => 'Salary From',
	'table' => 'recruitment_request',
	'column' => 'salary_from',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][2]['recruitment_request.salary_to'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Salary To',
	'description' => 'Salary To',
	'table' => 'recruitment_request',
	'column' => 'salary_to',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][2]['recruitment_request.budget_from'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Budget From',
	'description' => 'Budget From',
	'table' => 'recruitment_request',
	'column' => 'budget_from',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);

$config['fields'][2]['recruitment_request.budget_to'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Budget To',
	'description' => 'Budget To',
	'table' => 'recruitment_request',
	'column' => 'budget_to',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.closing_remarks'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Closing Remarks',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'closing_remarks',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.closed_by'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Closed By',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'closed_by',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['recruitment_request.closed_on'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Closed on',
	'description' => '',
	'table' => 'recruitment_request',
	'column' => 'closed_on',
	'uitype_id' => 16,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);