<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][2]['memo.attachment'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Attachment',
	'description' => 'Attachment',
	'table' => 'memo',
	'column' => 'attachment',
	'uitype_id' => 8,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['memo.memo_type_id'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Memo Type',
	'description' => 'Select a memorandum type',
	'table' => 'memo',
	'column' => 'memo_type_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'memo_type',
		'multiple' => 1,
		'group_by' => '',
		'label' => 'memo_type',
		'value' => 'memo_type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['memo.apply_to_id'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Recipient',
	'description' => 'Select who are the recipients',
	'table' => 'memo',
	'column' => 'apply_to_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'memo_apply_to',
		'multiple' => 1,
		'group_by' => '',
		'label' => 'apply_to',
		'value' => 'apply_to_id',
		'textual_value_column' => ''
	)
);
$config['fields'][1]['memo.memo_title'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Memo Title',
	'description' => 'Name of the memorandum',
	'table' => 'memo',
	'column' => 'memo_title',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['memo.publish_from'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Publish From',
	'description' => '',
	'table' => 'memo',
	'column' => 'publish_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['memo.publish_to'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Publish To',
	'description' => '',
	'table' => 'memo',
	'column' => 'publish_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['memo.publish'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Publish',
	'description' => '',
	'table' => 'memo',
	'column' => 'publish',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['memo.comments'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Allow Comments',
	'description' => '',
	'table' => 'memo',
	'column' => 'comments',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['memo.memo_body'] = array(
	'f_id' => 8,
	'fg_id' => 2,
	'label' => 'Memo Body',
	'description' => '',
	'table' => 'memo',
	'column' => 'memo_body',
	'uitype_id' => 5,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['memo.email'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Email Recipients',
	'description' => '',
	'table' => 'memo',
	'column' => 'email',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
