<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['partners_clinic_records.details'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Details',
	'description' => '',
	'table' => 'partners_clinic_records',
	'column' => 'details',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_clinic_records.attachments'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Attachments',
	'description' => '',
	'table' => 'partners_clinic_records',
	'column' => 'attachments',
	'uitype_id' => 8,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_clinic_records.other_med_cost'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Other Medication Cost',
	'description' => '',
	'table' => 'partners_clinic_records',
	'column' => 'other_med_cost',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_clinic_records.diagnosis'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Diagnosis',
	'description' => '',
	'table' => 'partners_clinic_records',
	'column' => 'diagnosis',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_clinic_records.complaint'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Complaint',
	'description' => '',
	'table' => 'partners_clinic_records',
	'column' => 'complaint',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_clinic_records.medication_qty'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Medication Quantity ',
	'description' => '',
	'table' => 'partners_clinic_records',
	'column' => 'medication_qty',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_clinic_records.medication'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Medication ',
	'description' => '',
	'table' => 'partners_clinic_records',
	'column' => 'medication',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['partners_clinic_records.partner_id'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Partner',
	'description' => '',
	'table' => 'partners_clinic_records',
	'column' => 'partner_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'alias',
		'value' => 'partner_id',
		'textual_value_column' => ''
	)
);
