	<script type="text/javascript" src="{{ theme_path() }}plugins/gritter/js/jquery.gritter.js"></script>
    <script type="text/javascript" src="{{ theme_path() }}plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
    <script type="text/javascript" src="{{ theme_path() }}plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="{{ theme_path() }}plugins/holder.js"></script>
	<script type="text/javascript" src="{{ theme_path() }}plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>	
    <script type="text/javascript" src="{{ theme_path() }}plugins/fuelux/js/spinner.min.js"></script>
	<script type="text/javascript" src="{{ theme_path() }}plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
	<script type="text/javascript" src="{{ theme_path() }}plugins/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
	<script type="text/javascript" src="{{ theme_path() }}plugins/bootstrap-touchspin/bootstrap.touchspin.js"></script>